### ISSUE TITLE
应用启动时无法找到类"com.taobao.windmill.bundle.bridge.WeexBridge"

### ISSUE THREAD

**Issue by mattu79** [chameleon-team/chameleon-sdk-android#4]
chameleon-sdk-android编译启动时出现以下错误，ndk设置了abiFilters "x86", "armeabi"同时换了多种cpu的模拟器依然无效。
> Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
> D/CmlWeexEngine: init cml weex engine
> E/WXSDKEngine: WXEnvironment.sApplication is null
> W/linker: libweexcore.so: unused DT entry: type 0x6ffffffe arg 0x480a0
>     libweexcore.so: unused DT entry: type 0x6fffffff arg 0x3
> I/art: Background sticky concurrent mark sweep GC freed 2443(191KB) AllocSpace objects, 1(16KB) LOS objects, 14% free, 954KB/1117KB, paused 16.070ms total 37.519ms
> D/CmlDiskLruCache: CmlDiskLruCache init, cacheDir=/storage/sdcard/Android/data/com.didi.chameleon.example/cache/cml/preload
> E/WeexCore: failed find class WMBridge
> W/System.err: java.lang.ClassNotFoundException: Didn't find class "com.taobao.windmill.bundle.bridge.WeexBridge" on path: DexPathList[[zip file "/data/app/com.didi.chameleon.example-2/base.apk"],nativeLibraryDirectories=[/data/app/com.didi.chameleon.example-2/lib/x86, /vendor/lib, /system/lib]]
>         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
> W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
>         at java.lang.Runtime.nativeLoad(Native Method)
>         at java.lang.Runtime.doLoad(Runtime.java:428)
>         at java.lang.Runtime.loadLibrary(Runtime.java:369)
>         at java.lang.System.loadLibrary(System.java:988)
>         at com.taobao.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:133)
> D/CmlDiskLruCache: CmlDiskLruCache init, cacheDir=/storage/sdcard/Android/data/com.didi.chameleon.example/cache/cml/common
> W/System.err:     at com.taobao.weex.WXSDKEngine$1.run(WXSDKEngine.java:227)
>         at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
>         at android.os.Handler.handleCallback(Handler.java:739)
>         at android.os.Handler.dispatchMessage(Handler.java:95)
>         at android.os.Looper.loop(Looper.java:135)
>         at android.os.HandlerThread.run(HandlerThread.java:61)
>     	Suppressed: java.lang.ClassNotFoundException: com.taobao.windmill.bundle.bridge.WeexBridge
>         at java.lang.Class.classForName(Native Method)
>         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
>         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
>     		... 12 more
>     	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
> D/SimpleComponentHolder: Generate Component:WXText
> D/SimpleComponentHolder: Generate Component:WXDiv
> D/SimpleComponentHolder: Generate Component:WXImage
> D/SimpleComponentHolder: Generate Component:WXScroller
> D/SimpleComponentHolder: Generate Component:WXSlider
> D/SimpleComponentHolder: Generate Component:WXSliderNeighbor
> D/SimpleComponentHolder: Generate Component:WXCell
> D/SimpleComponentHolder: Generate Component:WXListComponent

**Comment by mattu79** [comment]
可能是weex_sdk的问题，将weex_sdk降级到0.20.3.0-beta版本，就不会报这个错了。
